### ISSUE TITLE
the result seed is no longer selectable

### ISSUE THREAD

**Issue by wingstrong** [cmdr2/stable-diffusion-ui#661] opened 2022-12-14 19:39 UTC
**Is your feature request related to a problem? Please describe.**

please return the possibility to select a seed of the result so that I can copy it and paste into the seed input field to avoid having to remember the 7-digit number (to see which I have to scroll down the screen)

**Comment by JeLuF** [comment] 2022-12-15 13:22
I'm a little bit confused since there was no change in this area.

If you hover over a generated image, the seed used for this image is shown in the top right corner:
![image](https://user-images.githubusercontent.com/5852422/207869824-bcca20e6-e557-48a2-82b4-32d84a5407ba.png)

**Comment by JeLuF** [comment] 2022-12-15 15:39
Which version of Stable Diffusion UI are you using?
Do you have any plugins installed?
Are there any error messages in the browser's developer console (Right click into the browser window -> "Inspect", then navigate to the `console` tab)?

**Comment by wingstrong** [comment] 2022-12-15 16:07
v2.4.19
Plugins for SD? No, only Custom VAE.
I don't understand developer consoles as I'm not a programmer and don't understand English (I need a translator everywhere)

**Comment by Z3R0C1PH3R** [comment] 2022-12-19 06:20
Same, i am not able to select the seed as clicking and dragging to select the text selects the whole image

https://user-images.githubusercontent.com/59080407/208360693-ad529aed-710e-4ae9-ba73-f8d198bbbdb2.mp4

**Comment by JeLuF** [comment] 2022-12-19 07:16
I've been able to reproduce the issue. PR #675 fixes this. It has been merged in beta and will be in `main` in a few days.

**Closed** 2023-05-08 10:28 UTC
Labels: enhancement
