### ISSUE TITLE
Could not fetch URL https://pypi.org/simple/torch/

### ISSUE THREAD

**Issue by ange841** [cmdr2/stable-diffusion-ui#1147] opened 2023-04-11 03:33 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment] 2023-04-11 17:29
Duplicate of #1148

**Closed** 2023-05-08 10:46 UTC
Labels: bug
