### ISSUE TITLE
All files in the root of stable-diffusion-ui\stable-diffusion deleted

### ISSUE THREAD

**Issue by somenewaccountthen** [cmdr2/stable-diffusion-ui#67] opened 2022-09-05 17:46 UTC
Steps to reproduce.

1. cd C:\stable-diffusion-ui\
2. run: scripts\Start Stable Diffusion UI.cmd
3. wait till it is running.
4. press ctrl-c in the console
5. click **N**
6. prompt "press any key to continue" (Files still there at this stage)
7. Press any key.
8. All files in stable-diffusion-ui\stable-diffusion gone.

Choosing Y in step 5 will not delete the files.

**Comment by cmdr2** [comment] 2022-09-06 15:44
Hi, I believe you've already got the UI working several times, based on your messages on the Discord server, and the images you've posted.

I also just ran the steps you posted above. I waited till it started, then pressed ctrl-c, then pressed N, then pressed any key to continue. All the files in stable-diffusion were still there.

Like I said, there is no code here that deletes any file. Conda doesn't delete the stable diffusion code either. I would have to ask you to please check your system.

Also, if you just want to close to server, please just press the 'X' button at the top right of the command window. There is no need to press Ctrl-C.

I'm closing this issue since the problem is not reproducible on any other computer.

**Closed by cmdr2** 2022-09-06 15:44 UTC
